In [1]:
import tensorflow as tf
import numpy as np
from tf_transfer.constants import *

In [309]:
test = np.array([
    [[item + '00' for item in VECTORS_DIRECTIONS_NEW], [item + '01' for item in VECTORS_DIRECTIONS_NEW], [item + '02' for item in VECTORS_DIRECTIONS_NEW]],
    [[item + '10' for item in VECTORS_DIRECTIONS_NEW], [item + '11' for item in VECTORS_DIRECTIONS_NEW], [item + '12' for item in VECTORS_DIRECTIONS_NEW]],
    [[item + '20' for item in VECTORS_DIRECTIONS_NEW], [item + '21' for item in VECTORS_DIRECTIONS_NEW], [item + '22' for item in VECTORS_DIRECTIONS_NEW]],
])

test_22 = np.array([
    [[item + '00' for item in VECTORS_DIRECTIONS_NEW], [item + '01' for item in VECTORS_DIRECTIONS_NEW], ],
    [[item + '10' for item in VECTORS_DIRECTIONS_NEW], [item + '11' for item in VECTORS_DIRECTIONS_NEW], ],
])



In [118]:
for i, cx, cy in zip(VECTOR_INDEXES, VECTORS_VELOCITIES_X, VECTORS_VELOCITIES_Y):
    pass
np.roll(test[:, :, i], (cx, cy), axis=(1, 0))

array([['SE12', 'SE10', 'SE11'],
       ['SE22', 'SE20', 'SE21'],
       ['SE02', 'SE00', 'SE01']], dtype='<U4')

In [110]:
print(cx, cy)

1 -1


In [121]:
test[:, :, i][:, :1]

array([['SE00'],
       ['SE10'],
       ['SE20']], dtype='<U4')

In [18]:
test

array([[['NWa', 'Na', 'NEa', 'Wa', 'Ca', 'Ea', 'SWa', 'Sa', 'SEa'],
        ['NWb', 'Nb', 'NEb', 'Wb', 'Cb', 'Eb', 'SWb', 'Sb', 'SEb']],

       [['NWc', 'Nc', 'NEc', 'Wc', 'Cc', 'Ec', 'SWc', 'Sc', 'SEc'],
        ['NWd', 'Nd', 'NEd', 'Wd', 'Cd', 'Ed', 'SWd', 'Sd', 'SEd']]],
      dtype='<U3')

In [29]:
test[0:2, 0:2, CYL_BOUNCE_BACK_DIRECTIONS_NEW]

array([[['SEa', 'Sa', 'SWa', 'Ea', 'Ca', 'Wa', 'NEa', 'Na', 'NWa'],
        ['SEb', 'Sb', 'SWb', 'Eb', 'Cb', 'Wb', 'NEb', 'Nb', 'NWb']],

       [['SEc', 'Sc', 'SWc', 'Ec', 'Cc', 'Wc', 'NEc', 'Nc', 'NWc'],
        ['SEd', 'Sd', 'SWd', 'Ed', 'Cd', 'Wd', 'NEd', 'Nd', 'NWd']]],
      dtype='<U3')

In [40]:
test_sl = []
for idx in CYL_BOUNCE_BACK_DIRECTIONS_NEW:
    test_sl.append(test[:, :, idx])

In [50]:
np.concatenate(test_sl, axis=1)
np.stack(test_sl, axis=2)

array([[['SEa', 'Sa', 'SWa', 'Ea', 'Ca', 'Wa', 'NEa', 'Na', 'NWa'],
        ['SEb', 'Sb', 'SWb', 'Eb', 'Cb', 'Wb', 'NEb', 'Nb', 'NWb']],

       [['SEc', 'Sc', 'SWc', 'Ec', 'Cc', 'Wc', 'NEc', 'Nc', 'NWc'],
        ['SEd', 'Sd', 'SWd', 'Ed', 'Cd', 'Wd', 'NEd', 'Nd', 'NWd']]],
      dtype='<U3')

In [30]:
test_arr = np.array([
    [np.arange(9), np.arange(9)],
    [np.arange(9), np.arange(9)],
])

In [96]:
tf_test_arr = tf.Variable(test_arr)

In [104]:
tf_test_arr[:, :, 0]

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40]])>

In [102]:
tf_test_arr[:2, :2, 0].assign([[10, 20], [30, 40]])

<tf.Variable 'UnreadVariable' shape=(2, 2, 9) dtype=int64, numpy=
array([[[10,  1,  2,  3,  4,  5,  6,  7,  8],
        [20,  1,  2,  3,  4,  5,  6,  7,  8]],

       [[30,  1,  2,  3,  4,  5,  6,  7,  8],
        [40,  1,  2,  3,  4,  5,  6,  7,  8]]])>

In [78]:
np.arange(9) * np.ones(36).reshape(9, 9).T

ValueError: cannot reshape array of size 36 into shape (9,9)

In [95]:
def boundary_init(shape, dtype=None, partition_info=None):
    kernel = np.zeros(shape)
    kernel[0, 0, :, :] = tf.constant(np.array([
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]
    ])
    )
    return tf.cast(kernel, dtype)

boundary_conv = tf.keras.layers.Conv2D(9, (1, 1), kernel_initializer=boundary_init)
batch = (np.arange(9, dtype=np.float32)).reshape(1, 1, 1, 9)
# batch = (VECTORS_DIRECTIONS_NEW).reshape(1, 1, 1, 9)
boundary_conv(batch)

<tf.Tensor: shape=(1, 1, 1, 9), dtype=float32, numpy=array([[[[8., 7., 6., 5., 4., 3., 2., 1., 0.]]]], dtype=float32)>

In [418]:
lattice_idx_to_kernel = [2, 1, 0, 5, 4, 3, 8, 7, 6]
lattice_idx_to_kernel = [
    (0, 2), (0, 1), (0, 0),
    (1, 2), (1, 1), (1, 0),
    (2, 2), (2, 1), (2, 0)
]

# kernel for np.roll replacement
def roll_init(shape, dtype=None, partition_info=None):
    kernel = np.zeros(shape)
    print(kernel.shape)
    ker11 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 2 - idx 2
    ]).reshape(9, 1)
    ker12 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 1 - idx 1
    ]).reshape(9, 1)
    ker13 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 0 - id 0
    ]).reshape(9, 1)
    ker21 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 5 - idx 5
    ]).reshape(9, 1)
    ker22 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 4 - idx 4
    ]).reshape(9, 1)
    ker23 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 3 - idx 3
    ]).reshape(9, 1)
    ker31 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 1.],  # 8 - idx 8
    ]).reshape(9, 1)
    ker32 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 7 - idx 7
    ]).reshape(9, 1)
    ker33 = np.array([
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],  # 6 - idx 6
    ]).reshape(9, 1)

    # cy == -1 --> shift three indexes to left without permutation
    # cx == 1  --> permute `pattern` 0, 1, 2 -> 1, 2, 0  # np.roll(np.arange(3), -1)
    # cx == -1 --> permute `pattern` 0, 1, 2 -> 2, 1, 0  # np.roll(np.arange(3), 1)
    # `i` in the loop means what row kernel row should be modified
    # kernel number - which lattice is processed
    # New
    # kernel column - which items to take from lattice
    # Old:
    # kernel row - which items to take
    # kernel column - at which result  position value will appear
    # 3, 3, 9, 9
    # 3, 3, 9, 1
    kernel[:, :, :, :] = tf.constant(np.array([
      [ker11, ker12, ker13],  
      [ker21, ker22, ker23],  
      [ker31, ker32, ker33],  
    ]))
    return tf.cast(kernel, dtype)

roll_conv = tf.keras.layers.Conv2D(1, (3, 3), kernel_initializer=roll_init)
batch = (np.expand_dims(indexes, axis=0)).astype(np.float32)
batch_processed = tf.squeeze(roll_conv(batch)).numpy().astype(np.int32)
batch_processed


(3, 3, 9, 1)


68

In [432]:
lattice_idx_to_kernel = [
    (0, 2), (0, 1), (0, 0),
    (1, 2), (1, 1), (1, 0),
    (2, 2), (2, 1), (2, 0)
]

roll_kernels = []
for vector_idx, lattice_idx in zip(VECTOR_INDEXES, lattice_idx_to_kernel):
    kernels = np.zeros((3, 3, 9, 1))
    kernels[lattice_idx[0], lattice_idx[1], vector_idx] = 1
    roll_kernels.append(kernels)

def roll_init(shape, dtype=None, partition_info=None):
    print(KERNEL)
    return tf.cast(tf.constant(KERNEL), dtype)

def get_roll_init(kernel):
    kernel_local = kernel
    def roll_init(shape, dtype=None, partition_info=None):
        return tf.cast(tf.constant(kernel_local), dtype)
    return roll_init

roll_convs = []
for idx in range(9):
    KERNEL = roll_kernels[idx]
    roll_convs.append(tf.keras.layers.Conv2D(
        1, (3, 3), kernel_initializer=get_roll_init(KERNEL),
        padding='same', strides=1)
    )


In [435]:
batch = (np.expand_dims(indexes, axis=0)).astype(np.float32)
batch_processed = tf.squeeze(roll_convs[i](batch)).numpy().astype(np.int32)
batch_processed

array([[ 0,  0,  0],
       [10, 20,  0],
       [40, 50,  0]], dtype=int32)

In [434]:
i = 0
cx, cy = VECTORS_VELOCITIES_X[i], VECTORS_VELOCITIES_Y[i]
print("# i:", i, "cx:", cx, "cy:", cy)

indexes_rolled = indexes.copy()
indexes_rolled[:, :, i] = np.roll(indexes[:3, :3, i], (cx, cy), axis=(1, 0))
print(np.roll(indexes[:3, :3, i], (cx, cy), axis=(1, 0)))
print(np.roll(indexes[:3, :3, i], (cx, cy), axis=(1, 0))[1, 1])

# i: 0 cx: -1 cy: 1
[[70 80 60]
 [10 20  0]
 [40 50 30]]
20


In [274]:
def build_roll_kernel(element_idx, cx, cy):
    cx_pattern = [0, 1, 2]
    cx_moves = np.roll(cx_pattern, -cx)
    cy_pattern = [0, 1, 2]
    cy_moves = np.roll(cy_pattern, -cy)
    kernels = []
    for cy_move in cy_moves:
        kerlens_line = []
        for cx_move in cx_moves:
            kernel = np.zeros((9, 9))
            inner_idx = cy_move * 3 + cx_move
            kernel[element_idx][inner_idx] = 1.0
            kerlens_line.append(kernel)
        kernels.append(kerlens_line)
    return np.array(kernels)


def roll_init(shape, dtype=None, partition_info=None):
    return tf.cast(tf.constant(KERNEL), dtype)

roll_kernels = [build_roll_kernel(i, cx, cy) for i, cx, cy in
                zip(VECTOR_INDEXES, VECTORS_VELOCITIES_X, VECTORS_VELOCITIES_Y)]
for i, cx, cy in zip(VECTOR_INDEXES, VECTORS_VELOCITIES_X, VECTORS_VELOCITIES_Y):
    KERNEL = roll_kernels[i]
    roll_conv = tf.keras.layers.Conv2D(9, (3, 3), kernel_initializer=roll_init)
    batch = (np.expand_dims(indexes, axis=0)).astype(np.float32)
    batch_processed = tf.squeeze(roll_conv(batch)).numpy().astype(np.int32)
    assert np.all(batch_processed == np.roll(indexes[:, :, i], (cx, cy), axis=(1, 0)).reshape(-1))


In [365]:
i

8

58

In [369]:
indexes[:2, :2, i]

array([[ 8, 18],
       [38, 48]])

In [280]:
dtype = tf.float32
F_init = init_poiseuille()
F_tf = tf.Variable(F_init, dtype=dtype)

In [283]:
wide_F = np.zeros((F_init.shape[0] + 2, F_init.shape[1] + 2, 9))

In [299]:
F_init[-1]

array([[0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719],
       [0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719],
       [0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719],
       ...,
       [0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719],
       [0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719],
       [0.02794906, 0.11111041, 0.02760719, ..., 0.02794906, 0.11111041,
        0.02760719]])

In [346]:
dtype = tf.float32
F_init = init_poiseuille()
wide_F = np.zeros((F_init.shape[0] + 2, F_init.shape[1] + 2, 9))

wide_F[1:-1, 1:-1, :] = F_init
wide_F[0, 1:-1, :] = F_init[-1, :, :]
wide_F[-1, 1:-1, :] = F_init[0, :, :]
wide_F[1:-1, 0, :] = F_init[:, -1, :]
wide_F[1:-1, -1, :] = F_init[:, 0, :]
wide_F[0, 0, :] = F_init[-1, -1, :]
wide_F[-1, -1, :] = F_init[0, 0, :]
wide_F[0, -1, :] = F_init[-1, 0, :]
wide_F[-1, 0, :] = F_init[0, -1, :]

In [341]:
F_init.shape

(100, 400, 9)

In [349]:
F_tf = tf.Variable(F_init, dtype=dtype)
wide_F = np.zeros((F_init.shape[0] + 2, F_init.shape[1] + 2, 9))
wide_F_tf = tf.Variable(wide_F)
wide_F_tf[1:-1, 1:-1, :].assign(F_init)
wide_F_tf[0, 1:-1, :].assign(F_init[-1, :, :])
wide_F_tf[-1, 1:-1, :].assign(F_init[0, :, :])
wide_F_tf[1:-1, 0, :].assign(F_init[:, -1, :])
wide_F_tf[1:-1, -1, :].assign(F_init[:, 0, :])
wide_F_tf[0, 0, :].assign(F_init[-1, -1, :])
wide_F_tf[-1, -1, :].assign(F_init[0, 0, :])
wide_F_tf[0, -1, :].assign(F_init[-1, 0, :])
wide_F_tf[-1, 0, :].assign(F_init[0, -1, :]);


In [358]:
F_tf.shape

TensorShape([100, 400, 9])

In [357]:
wide_F_tf_batch = tf.expand_dims(wide_F_tf, axis=0)
tf.squeeze(roll_convs[0](wide_F_tf_batch))[1:-1, 1:-1, :]

<tf.Tensor: shape=(100, 400, 9), dtype=float32, numpy=
array([[[0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719],
        ...,
        [0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02760719, 0.02760719, 0.02760719, ..., 0.02760719,
         0.02760719, 0.02760719]],

       [[0.02794732, 0.02794732, 0.02794732, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02794732, 0.02794732, 0.02794732, ..., 0.02760719,
         0.02760719, 0.02760719],
        [0.02794732, 0.02794732, 0.02794732, ..., 0.02760719,
         0.02760719, 0.02760719],
        ...,
        [0.02794732, 0.02794732, 0.02794732, ..., 0.0

In [340]:
for i, cx, cy in zip(VECTOR_INDEXES, VECTORS_VELOCITIES_X, VECTORS_VELOCITIES_Y):
    wide_F[:, :, i] = np.roll(wide_F[:, :, i], (cx, cy), axis=(1, 0))
    
for i, cx, cy in zip(VECTOR_INDEXES, VECTORS_VELOCITIES_X, VECTORS_VELOCITIES_Y):
    F_init[:, :, i] = np.roll(F_init[:, :, i], (cx, cy), axis=(1, 0))
    
np.all(wide_F[1:-1, 1:-1, :] == F_init)

True

# Debug cells for rolls indexing

In [262]:
np.roll(indexes[:, :, i], (cx, cy), axis=(1, 0)).reshape(-1)

array([13, 23,  3, 43, 53, 33, 73, 83, 63])

In [261]:
i = 3
cx, cy = VECTORS_VELOCITIES_X[i], VECTORS_VELOCITIES_Y[i]
print("# i:", i, "cx:", cx, "cy:", cy)
indexes = np.array([
    [np.arange(9), np.arange(10, 19), np.arange(20, 29),],
    [np.arange(30, 39), np.arange(40, 49), np.arange(50, 59),],
    [np.arange(60, 69), np.arange(70, 79), np.arange(80, 89),],
])
indexes_roll = np.copy(indexes)
indexes_roll[:, :, i] = np.roll(indexes[:, :, i], (cx, cy), axis=(1, 0))

# i: 3 cx: -1 cy: 0


In [275]:
indexes.shape

(3, 3, 9)

In [248]:
indexes_roll

array([[[ 0,  1,  2,  3,  4, 25,  6,  7,  8],
        [10, 11, 12, 13, 14,  5, 16, 17, 18],
        [20, 21, 22, 23, 24, 15, 26, 27, 28]],

       [[30, 31, 32, 33, 34, 55, 36, 37, 38],
        [40, 41, 42, 43, 44, 35, 46, 47, 48],
        [50, 51, 52, 53, 54, 45, 56, 57, 58]],

       [[60, 61, 62, 63, 64, 85, 66, 67, 68],
        [70, 71, 72, 73, 74, 65, 76, 77, 78],
        [80, 81, 82, 83, 84, 75, 86, 87, 88]]])

In [152]:
print(cx, cy)

1 -1
