In [1]:
import tensorflow as tf
import numpy as np
from tf_transfer.constants import *

In [17]:
test = np.array([
    [[item + 'a' for item in VECTORS_DIRECTIONS_NEW], [item + 'b' for item in VECTORS_DIRECTIONS_NEW]],
    [[item + 'c' for item in VECTORS_DIRECTIONS_NEW], [item + 'd' for item in VECTORS_DIRECTIONS_NEW]],
])

In [18]:
test

array([[['NWa', 'Na', 'NEa', 'Wa', 'Ca', 'Ea', 'SWa', 'Sa', 'SEa'],
        ['NWb', 'Nb', 'NEb', 'Wb', 'Cb', 'Eb', 'SWb', 'Sb', 'SEb']],

       [['NWc', 'Nc', 'NEc', 'Wc', 'Cc', 'Ec', 'SWc', 'Sc', 'SEc'],
        ['NWd', 'Nd', 'NEd', 'Wd', 'Cd', 'Ed', 'SWd', 'Sd', 'SEd']]],
      dtype='<U3')

In [29]:
test[0:2, 0:2, CYL_BOUNCE_BACK_DIRECTIONS_NEW]

array([[['SEa', 'Sa', 'SWa', 'Ea', 'Ca', 'Wa', 'NEa', 'Na', 'NWa'],
        ['SEb', 'Sb', 'SWb', 'Eb', 'Cb', 'Wb', 'NEb', 'Nb', 'NWb']],

       [['SEc', 'Sc', 'SWc', 'Ec', 'Cc', 'Wc', 'NEc', 'Nc', 'NWc'],
        ['SEd', 'Sd', 'SWd', 'Ed', 'Cd', 'Wd', 'NEd', 'Nd', 'NWd']]],
      dtype='<U3')

In [40]:
test_sl = []
for idx in CYL_BOUNCE_BACK_DIRECTIONS_NEW:
    test_sl.append(test[:, :, idx])

In [50]:
np.concatenate(test_sl, axis=1)
np.stack(test_sl, axis=2)

array([[['SEa', 'Sa', 'SWa', 'Ea', 'Ca', 'Wa', 'NEa', 'Na', 'NWa'],
        ['SEb', 'Sb', 'SWb', 'Eb', 'Cb', 'Wb', 'NEb', 'Nb', 'NWb']],

       [['SEc', 'Sc', 'SWc', 'Ec', 'Cc', 'Wc', 'NEc', 'Nc', 'NWc'],
        ['SEd', 'Sd', 'SWd', 'Ed', 'Cd', 'Wd', 'NEd', 'Nd', 'NWd']]],
      dtype='<U3')

In [30]:
test_arr = np.array([
    [np.arange(9), np.arange(9)],
    [np.arange(9), np.arange(9)],
])

In [96]:
tf_test_arr = tf.Variable(test_arr)

In [104]:
tf_test_arr[:, :, 0]

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40]])>

In [102]:
tf_test_arr[:2, :2, 0].assign([[10, 20], [30, 40]])

<tf.Variable 'UnreadVariable' shape=(2, 2, 9) dtype=int64, numpy=
array([[[10,  1,  2,  3,  4,  5,  6,  7,  8],
        [20,  1,  2,  3,  4,  5,  6,  7,  8]],

       [[30,  1,  2,  3,  4,  5,  6,  7,  8],
        [40,  1,  2,  3,  4,  5,  6,  7,  8]]])>

In [78]:
np.arange(9) * np.ones(36).reshape(9, 9).T

ValueError: cannot reshape array of size 36 into shape (9,9)

In [95]:
def boundary_init(shape, dtype=None, partition_info=None):
    kernel = np.zeros(shape)
    kernel[0, 0, :, :] = tf.constant(np.array([
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]
    ])
    )
    return tf.cast(kernel, dtype)

boundary_conv = tf.keras.layers.Conv2D(9, (1, 1), kernel_initializer=boundary_init)
batch = (np.arange(9, dtype=np.float32)).reshape(1, 1, 1, 9)
# batch = (VECTORS_DIRECTIONS_NEW).reshape(1, 1, 1, 9)
boundary_conv(batch)

<tf.Tensor: shape=(1, 1, 1, 9), dtype=float32, numpy=array([[[[8., 7., 6., 5., 4., 3., 2., 1., 0.]]]], dtype=float32)>

In [86]:
kernel = np.zeros((9, 9))
for idx_from, idx_to in enumerate(CYL_BOUNCE_BACK_DIRECTIONS_NEW):
    kernel[idx_from, idx_to] = 1

In [91]:
kernel

array([[0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])